import { useEffect, useRef, useState } from 'react'
import './App.css'
import './portrait.css'

const sounds = [['♩','Upright Bass','Four strings, deep pocket.'],['⌁','Bass Guitar','The heartbeat of the room.'],['♬','Guitar','A little rhythm, a little shine.'],['●','Vocals','Say it so folks can feel it.'],['⌂','Basement Sessions','The best seat is saved.']]
const impulse=(ctx,room)=>{const n=Math.floor(ctx.sampleRate*(.3+room*.024)),b=ctx.createBuffer(2,n,ctx.sampleRate);for(let c=0;c<2;c++){const d=b.getChannelData(c);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n)**2}return b}

export default function App(){
 const [recording,setRecording]=useState(false),[blob,setBlob]=useState(null),[url,setUrl]=useState(''),[status,setStatus]=useState('Tap Record when you are ready. Your recording stays on this device.'),[playing,setPlaying]=useState(false),[song,setSong]=useState(''),[artist,setArtist]=useState(''),[source,setSource]=useState('imslp')
 const [warmth,setWarmth]=useState(48),[echo,setEcho]=useState(16),[room,setRoom]=useState(24),[pitch,setPitch]=useState(0)
 const rec=useRef(),audio=useRef(),ctx=useRef(),nodes=useRef()
 useEffect(()=>{if(!blob)return;const next=URL.createObjectURL(blob);setUrl(next);return()=>URL.revokeObjectURL(next)},[blob])
 const graph=()=>{if(nodes.current)return nodes.current;const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;const c=new C(),s=c.createMediaElementSource(audio.current),f=c.createBiquadFilter(),d=c.createDelay(1.3),eg=c.createGain(),rv=c.createConvolver(),rg=c.createGain();f.type='lowpass';s.connect(f).connect(c.destination);s.connect(d).connect(eg).connect(c.destination);s.connect(rv).connect(rg).connect(c.destination);ctx.current=c;nodes.current={f,d,eg,rv,rg};return nodes.current}
 const tune=()=>{const n=nodes.current,c=ctx.current;if(!n)return;const t=c.currentTime;n.f.frequency.setTargetAtTime(7200-warmth*48,t,.04);n.d.delayTime.setTargetAtTime(.12+echo*.005,t,.04);n.eg.gain.setTargetAtTime(echo/145,t,.04);n.rv.buffer=impulse(c,room);n.rg.gain.setTargetAtTime(room/130,t,.04)}
 useEffect(()=>{tune();if(audio.current)audio.current.playbackRate=2**(pitch/12)},[warmth,echo,room,pitch])
 const toggle=async()=>{if(recording){rec.current.stop();setRecording(false);setStatus('Putting your take together…');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),r=new MediaRecorder(stream),chunks=[];rec.current=r;r.ondataavailable=e=>e.data.size&&chunks.push(e.data);r.onstop=()=>{setBlob(new Blob(chunks,{type:r.mimeType||'audio/webm'}));stream.getTracks().forEach(t=>t.stop());setStatus('That sounded good. Use Play, shape the sound, then save it.')};r.start();setRecording(true);setStatus('Recording now. Play whatever feels right.')}catch{setStatus('Your browser needs microphone permission before it can record.')}}
 const play=async()=>{if(!url){setStatus('Make a recording first, then it will be ready to play.');return}graph();if(ctx.current?.state==='suspended')await ctx.current.resume();tune();audio.current.playbackRate=2**(pitch/12);await audio.current.play();setPlaying(true);setStatus('Playing your take. Turn the controls while it plays.')}
 const save=()=>{if(!blob){setStatus('Record a little something first.');return}const a=document.createElement('a');a.href=url;a.download=`lennys-music-room-${new Date().toISOString().slice(0,10)}.${blob.type.includes('mp4')?'m4a':'webm'}`;a.click();setStatus('Your device is saving the recording. Look in Downloads or Files.')}
 const charts=e=>{e.preventDefault();const q=[song,artist,'sheet music'].filter(Boolean).join(' ');if(!q){setStatus('Add a song title first, then I can open a chart search.');return}const link=source==='imslp'?`https://imslp.org/index.php?title=Special:Search&search=${encodeURIComponent(q)}`:`https://musescore.com/sheetmusic?text=${encodeURIComponent(q)}`;window.open(link,'_blank','noopener,noreferrer');setStatus('Opening a chart search in a new tab. Check the license before downloading.')}
 return <main><header><a className="brand" href="#home"><span>♩</span> Lenny’s <em>Music Room</em></a><nav><a href="#player">Player</a><a href="#sound">Lenny’s Sound</a><a href="#charts">Find a chart</a></nav></header><section className="hero" id="home"><div><p className="eyebrow">Happy Father’s Day, Lenny.</p><h1>Pull up a chair.<br/>Make some music.</h1><p>Friends, soul, and good grooves have always belonged together in the basement.</p><p className="instruments">Bass guitar · upright bass · guitar · vocals</p></div></section><section className="studio" id="player"><section className="recording"><h2>The next session starts here.</h2><p className="status" role="status">{status}</p><div className="actions"><button className={'record '+(recording?'live':'')} onClick={toggle}><span>{recording?'■':'●'}</span>{recording?' Finish recording':' Record'}</button><button className="play" onClick={play} disabled={!url}>▶ Play it back</button></div><audio ref={audio} src={url} onEnded={()=>setPlaying(false)}/><p className="save"><button onClick={save} disabled={!url}>Save this recording</button>{playing&&<span>Now playing</span>}</p></section><section className="effects"><h2>Shape the sound</h2><Knob title="Warmth" value={warmth} set={setWarmth} max="100" copy="Make it smooth and rich."/><Knob title="Echo" value={echo} set={setEcho} max="70" copy="Add a little space."/><Knob title="Room" value={room} set={setRoom} max="70" copy="Set the basement feel."/><Knob title="Pitch" value={pitch} set={setPitch} min="-8" max="8" copy="Move it up or down gently." output={pitch===0?'just right':`${pitch>0?'+':''}${pitch} steps`}/></section></section><section className="lower"><section className="sound" id="sound"><h2>Lenny’s Sound</h2><p>Four strings, six strings, one good voice.</p><div className="sound-grid">{sounds.map(x=><article key={x[1]}><b>{x[0]}</b><h3>{x[1]}</h3><small>{x[2]}</small></article>)}</div></section><section className="charts" id="charts"><h2>Find a chart</h2><p>Search a legal music library without leaving the room.</p><form onSubmit={charts}><label>Song title<input value={song} onChange={e=>setSong(e.target.value)} placeholder="What are you playing?"/></label><label>Artist <i>(optional)</i><input value={artist} onChange={e=>setArtist(e.target.value)} placeholder="Who made it famous?"/></label><label>Search in<select value={source} onChange={e=>setSource(e.target.value)}><option value="imslp">IMSLP public-domain library</option><option value="musescore">MuseScore community library</option></select></label><button>Find a chart ↗</button></form><small>Not every song is free. Always check the chart’s license before using it.</small></section></section><footer>Made with love for Lenny Ball — where the groove lives.</footer></main>
}
function Knob({title,value,set,min=0,max,copy,output}){return <label className="knob"><span><b>{title}</b><small>{copy}</small></span><input type="range" min={min} max={max} value={value} onChange={e=>set(+e.target.value)} aria-label={title}/><output>{output||`${value}%`}</output></label>}
